#!/bin/bash

# Program to output System Info page

TITLE="System information Report for $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME, by $USER"

report_uptime () {
        return
}

report_disk_space (){
        df -f
        return
}

report_home_space (){
        du -sh /home/*
       return
}


cat << _EOF_
<html>
	<head>
		<title>$TITLE</title>
	</head>
	<body>
		<h1>$TITLE</h1>
		<p>$TIMESTAMP</p>
		$(report_upte)
		$(report_disk_space)
		$(report_home_space)
	</body>
</html>
_EOF_
