#!/bin/bash

TITLE="System Info for $HOSTNAME"
CR_TIME=$(date +"%x %r %Z")
TIMESTAMP="Generated $CR_TIME, by $USER"

echo "<html>
	<head>
		<title>$TITLE</title>
	</head>
	<body>
		<h1>$TITLE</h1>
		<p>$TIMESTAMP</p>
	</body>
</html>"
